matrix:
  include:
    - language: go
      before_install:
         - cp .netrc ~/.netrc 
         - chmod 600 ~/.netrc
      script: go run go/src/registration.go
    - language: node_js
      before_install: 
         - cd react-app
      addons:
          chrome: stable
      before_script:
         - google-chrome
      script: yarn start package.json
