matrix:
  include:
    - language: go
      before_install:
         - cp .netrc ~/.netrc 
         - chmod 600 ~/.netrc
      script: go run go/src/registration.go
    - language: node_js
      before_install:`
         - cd react-app
      node_js: 8.10.0
      dist: trusty
      addons:
         chrome: stable
      script: yarn start package.json
